### ISSUE TITLE
[BUG] how to resolve the problem ?   Non-base58 character

### ISSUE THREAD

**Issue by ChainCoderX** [monicanagent/cypherpoker.js#64]
under the server directory,

npm install 
node server.js 

bellowing message happens:

nitializing account system...
Error: Non-base58 character
    at Object.decode (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/node_modules/base-x/src/index.js:112:11)
    at Object.decode (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/node_modules/bs58check/base.js:39:25)
    at Object.fromBase58 (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/node_modules/bip32/index.js:213:26)
    at BlockstreamAPI.makeHDWallet (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/libs/adapters/BitcoinCoreNative.js:425:52)
    at createAccountSystem (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/server.js:1171:53)
    at postLoadConfig (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/server.js:1512:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by ChainCoderX** [comment]
hope help other people to resolve the problem.

            {
               "type": "cryptocurrency",
               "name": "Native Bitcoin Core (bitcoind) Handler",
               "installDir":"./bin/bitcoind/%os%/",
               "dataDir":"./bin/bitcoind/data/",
               "downloads":{
                  "darwin":"https://bitcoin.org/bin/bitcoin-core-0.18.0/bitcoin-0.18.0-osx.dmg",
                  "linux":"https://bitcoin.org/bin/bitcoin-core-0.18.0/bitcoin-0.18.0-x86_64-linux-gnu.tar.gz",
                  "win32":"https://bitcoin.org/bin/bitcoin-core-0.18.0/bitcoin-0.18.0-win64.zip"
               },
               "types": ["btc", "bitcoin", "tbtc", "testnet3", "test3", "testnet bitcoin"],
               "handlerClass": "./libs/adapters/BitcoinCoreNative.js",
               "showOutput": true,
               "enabled": true
            },

**Comment by monicanagent** [comment]
Thank you! :)
