### ISSUE TITLE
[BUG] Error: Could not create account.  on the frontend

### ISSUE THREAD

**Issue by ChainCoderX** [monicanagent/cypherpoker.js#65]
how to config the wallet network ??

Error: Wallet for "bitcoin", network "test3" not defined.
    at Promise (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/libs/adapters/BitcoinCoreNative.js:397:20)
    at new Promise (<anonymous>)
    at BlockstreamAPI.makeNewWallet (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/libs/adapters/BitcoinCoreNative.js:368:21)
    at Object.CP_Account (evalmachine.<anonymous>:65:51)
    at invokeAPIFunction (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/server.js:625:27)
    at processRPCRequest (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/server.js:557:9)
    at WebSocket.handleWSRequest (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/server.js:1002:3)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/wade/goworkspace/src/github.com/monicanagent/cypherpoker.js/src/server/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
Error: Wallet for "bitcoin", network "main" not defined.

**Comment by monicanagent** [comment]
Configuring the main cryptocurrency HD wallets is a 2-step process. First you need to create the actual wallets (private/public keys), and then you'll need to update the main [server config file](https://github.com/monicanagent/cypherpoker.js/blob/48e72a0cd80fb6384a43db1d562633a5e7bae529/src/server/config.json#L122-L143). The process is detailed in the following wiki: https://github.com/monicanagent/cypherpoker.js/wiki/Setting-up-a-private-home-game#3-configure-the-hd-wallets

Note that there are 4 individual entries, two for Bitcoin (main and testnet), and two for Bitcoin Cash (main and testnet).

There's a Node version of the HD wallet generator if you prefer that option: https://github.com/monicanagent/cypherpoker.js/blob/master/src/server/utils/newHDWallet.js

This process can _definitely_ be automated (it is a [part of the desktop setup](https://github.com/monicanagent/cypherpoker.js/blob/master/src/desktop/postinstall.js)), but it's one of the things I just haven't gotten around to. One person has expressed interest but if anyone else wants to take a crack at it, here's an open (and detailed) issue: https://github.com/monicanagent/cypherpoker.js/issues/48

When you're done, just restart the server and you should be able to re-create accounts on the front end. Because the system uses the HD architecture, re-created accounts will have the same credentials (private/public keys).

Be aware that unless you're using a database add-on like rdb (https://github.com/monicanagent/cypherpoker.js/blob/master/src/server/utils/rdb.php), the server will forget accounts and associated balances anytime it's restarted. In other words, it's an in-memory database. I'm working on creating a local file-based option but in the meantime you can re-create accounts in the browser anytime you restart the server simply by typing `localStorage.clear()` into the browser's [JavaScript console](https://www.geeksforgeeks.org/console-in-javascript/), and creating new accounts via the UI. No on-chain information will be lost, it's just an inconvenience (that will shortly be addressed). If you want to use the rdb option, let me know and I'll put together guide ... another task I haven't yet gotten around to :)

P.S. The wallets and derived HD accounts are all 100% valid BTC/BCH addresses + keys. If you wanted to, you could isolate this part of the code for use in other applications.

**Comment by ChainCoderX** [comment]
Got it.
Thanks.

**Comment by monicanagent** [comment]
Great :)
